steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - '$_PLATFORM'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - 'gestion-la-hornilla:us-central1:gestion-la-hornilla'
      - '--set-env-vars'
      - 'CLOUD_SQL_HOST=34.41.120.220,CLOUD_SQL_USER=UserApp,CLOUD_SQL_PASSWORD=&8y7c()tu9t/+,6`,CLOUD_SQL_DB=lahornilla_base_normalizada,JWT_SECRET_KEY=Inicio01*,SECRET_KEY=Inicio01*'

images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME' 